// 在 main_story.html 的 <script> 标签中，或在独立的 storyData.js 中定义
const mainStoryScript = [
    // === 故事正文开始 ===
    { action: 'changeBackground', bg: 'images/backgrounds/ui.png' },
    { character: 'reader', text: '嗯……你好？你们是？' },
    { character: 'rabbit', text: '你也看见了，刚刚那个“作者”，说着要让你了解”仙术杯“，但是什么都没做呢……总之，我们就是她派来带领你阅读这个故事的”导游“。' },
    { character: 'reader', text: '看对话框的标注，这两位一个叫”血狼破军“，一个叫“龙哥哥”，真是奇怪的名字……' },
    { character: 'reader', text: '（看向龙哥）' },
    { character: 'lgg', text: '（……剧烈的眼神躲闪，看起来恨不得原地消失……还是先跟另一个人搭话吧。）' },
    { character: 'reader', text: '？' },
    { character: 'rabbit', text: '哎？哈哈哈哈，抱歉抱歉，我朋友是个大社恐，现在我是他的“外置发声器官”喽。龙哥，这里好歹算是你的主场吧，不要怯场啊！' },
    { character: 'reader', text: '别的暂且不管吧……为什么说是“主场”呢？' },
    { character: 'rabbit', text: '之前那个“作者”也向你介绍了吧？这里主要讲的是游戏《明日方舟》的一个非官方赛事和它的选手们的故事……而龙哥嘛，他就是这个比赛的主办方&解说&选手！所以这里当然算他的主场啦' },
    { character: 'reader', text: '身兼这么多职真的没关系吗？' },
    { character: 'rabbit', text: '哎，毕竟龙哥真的很喜欢打游戏嘛！不过确实也有燃尽过，比如连着好几天解说到发烧了，还是很辛苦的。' },
    { character: 'writer', text: '啊，想到主办方举办赛事的辛苦，感觉自己连夜做这个网站的辛苦也没那么严重了啊。' },
    { character: 'reader', text: '不要比惨啊，而且你又是哪里冒出来的！把话说清楚再走啊！' },
    // === 场景切换至 scene3 ===
    { action: 'changeBackground', bg: 'images/backgrounds/directory_bg.jpg' },
    { character: 'reader', text: '又消失了……哇啊！' },
    { character: 'reader', text: '这又是哪？' },
    { character: 'rabbit', text: '唔，看场景是仙术杯#5的时候呢……' },
    { character: 'reader', text: '这个名字像选手id一样奇怪的比赛都第五届了吗？' },
    { character: 'rabbit', text: '实际上已经办到第七届了……想想还真是快呢。' },
    { character: 'reader', text: '要开始回忆了吗？一大段很煽情的那种？' },
    { character: 'rabbit', text: '没有那种环节……哎其实也可以有……' },
    { character: 'writer', text: '偷偷告诉你：此人曾因故形容他和龙哥乃黑暗面与光明面的关系。' },
    { character: 'rabbit', text: '咳咳！好了！我想想——仙术杯#5嘛——那那个不得不讲吧！是我们赛事圈子里很有名的故事呢——' },
    { character: 'writer', text: '从前，有两个选手，一个叫做剑圣kensei，一个叫维云斯，他们都参加了单人赛形式的仙术杯#3，却在赛后因为游戏理解的问题吵了起来——' },
    { character: 'reader', text: '奇怪的名字又增加了……以及你为什么又出现了……' },
    { character: 'writer', text: '惊天动地的吵！好吧其实是我们圈子不大所以啥事都很惊天动地，' },
    { character: 'writer', text: '其中，剑圣kensei作为仙术杯#3的冠军，对比赛成绩不理想的维云斯放话：你什么冠军？' },
    { character: 'writer', text: '结果呢，这两个人在采取团队赛形式的仙术杯#5，因为小队队长一手乱点鸳鸯谱，竟然阴差阳错地进了一个队伍！更戏剧化的是，他们还一起夺冠了——' },
    { character: 'writer', text: '由此诞生传奇老梗：你什么冠军😡？和你一起拿的冠军🥰！' },
    { character: 'rabbit', text: '所以你都讲完了我讲什么？' },
    { character: 'writer', text: '当然是起到关键的承上启下作用啊！不过其实我还兼职旁白啦>.<' },
    { character: 'reader', text: '发什么颜文字啊！不过，这段故事听起来确实很戏剧化……' },
    { character: 'writer', text: '是吧是吧？（看向血狼破军）' },
    { character: 'rabbit', text: '哎，看着我干什么？意思是现在轮到我来承上启下喽？' },
    { character: 'rabbit', text: '嗯……作为具有一定竞技性质的电子游戏赛事，选手们的操作也会给人留下很深刻的印象！例如前面提到过的维云斯，他的打法就算得上“绝活”！类似的绝活哥还有绵阳怪兽，一位打法灵活多变、刀尖舔血的选手！哎不对啊，这里不应该让周哥来讲吗？' },
    { character: 'reader', text: '这又是谁？需要记的名字太多了啦！' },
    { character: 'rabbit', text: '周哥可是我们小队里口才最好的一位！对哦，讲仙术杯#5怎么能忘了主办方和解说组队下场的故事呢？' },
    { character: 'reader', text: '？主办方正在热身？' },
    { character: 'rabbit', text: '哈哈！是的，就是我身边这位龙哥哥今天又鸽了，和三位好基友&流动解说——分别是米勒寒MillerRHan、魔法ZC目录、北绊半球——齐上阵，组成“冠军厨小队”，一起参加了比赛！然后，疑似本届比赛最大黑幕的队伍，全员没能完成比赛，因为种种原因错失角逐更高名次的机会了！' },
    { character: 'lgg', text: '讲的很开心的人不要忘了自己当时可是“名誉总教练”。俗话说的好，“全都怪血狼破军”。' },
    { character: 'rabbit', text: '这俗话也太野了。' },
    { character: 'reader', text: '把社恐都激到发话了吗？' },
    { character: 'reader', text: '结果这样配置的队伍根本没赢吗， 戏剧性还在增加……' },
    // === 场景回到主界面 ===
    { action: 'changeBackground', bg: 'images/backgrounds/ui.png' },
    { character: 'writer', text: '嗯嗯——是的！' },
    { character: 'writer', text: '总之，今天要讲的故事就到这里了！' },
    { character: 'reader', text: '哎？完全是戛然而止啊？' },
    { character: 'writer', text: '哈哈，肯定不是因为我要赶不上ddl了所以缩短了篇幅啊。不过，确实还有很多、很多的故事没有写到，除了欢笑和闹剧，也还有很多看不见的付出和努力。每一个选手为比赛付出的努力都是可敬的，每一位玩家为热爱坚持的恒心都是可爱的。作为7届比赛、四年时光的一个小小见证者，我希望能把我感受到的欢乐稍微地分享出来一点，祝福看到这里的你：天天开心，事事如意，有志同道合的朋友，有情有独钟的爱好！谢谢观看！' },
    { character: 'writer', text: '好啦，他们已经回到自己的世界啦~不过，作为你如今也见证了他们的一段故事的证明，他们的资料会留存在这里，你随时都可以查看（鉴赏立绘然后夸作者画的很努力）！' },
    // === 显示免责声明弹窗 ===

    { action: 'showDisclaimer' }
];